"""add another fileds

Revision ID: a1afa4349002
Revises: bcc64a0fe610
Create Date: 2023-10-28 16:21:30.442608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1afa4349002'
down_revision: Union[str, None] = 'bcc64a0fe610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('join_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('chat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chat_id')
    op.drop_column('users', 'join_date')
    op.drop_column('histories', 'datetime')
    # ### end Alembic commands ###
